import type { Scene, GameStartParams, GameStartResponse, NewSceneResponse } from '../types';

/**
 * Starts a new game session on the backend.
 * @param params - The initial parameters for the game (genre, ton, etc.).
 * @returns An object containing the new game ID and the prologue scene.
 */
export async function startGame(params: GameStartParams): Promise<GameStartResponse> {
  const response = await fetch('/api/game', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(params),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({ error: 'Failed to start game' }));
    throw new Error(errorData.error);
  }

  return response.json();
}

/**
 * Sends a player's choice to the backend for an ongoing game.
 * @param gameId - The ID of the current game session.
 * @param choice - The choice made by the player.
 * @returns The new scene generated by the game engine in response to the choice.
 */
export async function makeChoice(gameId: string, choice: string): Promise<NewSceneResponse> {
  const response = await fetch(`/api/game/${gameId}/choice`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ choice }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({ error: 'Failed to make a choice' }));
    throw new Error(errorData.error);
  }

  return response.json();
}
